### PR TITLE
Fix "mentionBg" and add "dndIndicator"

### PR DESCRIPTION
**Pull request by jaminthorns**
The "mentionBg" used to be "mentionBj" (Mattermost bug): https://mattermost.atlassian.net/browse/MM-7399

### CODE REVIEW

**Review by milouse — CHANGES_REQUESTED** [review]
Can you change the `mentionBj`, which is always present, to `#ff79c6` (and not `#ffffff`)? In order to be the same than `mentionBg`.

Thank you very much!

**Comment by jaminthorns** [comment]
Done!

**Comment by milouse** [comment]
All is good, thank you very much!

**Comment by milouse** [comment]
Wow, I just saw that I lost write access to this repository… I'll try to gain them back and merge ASAP. Sorry for the delay.

**Pull request merged**
